### ISSUE TITLE
Dependency on babel-eslint

### ISSUE THREAD

**Issue by dpiccone** [gustavnikolaj/onelint#14]
Just switched from v0.10.38 to v.4.2.2, and had to reinstall packages. It might be configuration specific but I had to ``` npm install -g babel-eslint ``` to make it work on PS.

**Comment by gustavnikolaj** [comment]
That's because of the package.json file in our project, that has a onelint section, that specifies that a different parser should be used.

```
{
  ...
  "onelint": {
    "parser": "babel-eslint"
  }
}
```

Normally onelint (standard-engine, actually) will use eslint, which will not work with some of the newer syntax - or maybe it's JSX - honestly, I don't remember :-)

The reason you needed to install it globally is probably, that you also install onelint globally.
